name: Release

on:
  release:
    types: [published]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  release:
    name: Create Release Asset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create zip archive
        run: |
          zip -r ha-expiration.zip custom_components/expiration

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: ha-expiration.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
